import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const inter = Roboto_Flex({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <nav className="fixed w-full h-16 z-30 px-[2vw] py[2vw] bg-[#f4f7f7]">
            <Navbar />
          </nav>
          <div className="flex flex-1 flex-col pt-16">
            <main className="flex-1 overflow-y-auto border-l bg-[#f4f7f7]">
              {children}
            </main>
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
